import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_brands_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_brands_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_brands_seo_sitemap_change_frequency" AS ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never');
  CREATE TYPE "public"."enum_brands_seo_schema_type" AS ENUM('auto', 'CollectionPage', 'WebPage', 'none');
  CREATE TYPE "public"."enum_products_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_products_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_products_seo_sitemap_change_frequency" AS ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never');
  CREATE TYPE "public"."enum_products_seo_schema_type" AS ENUM('auto', 'Product', 'WebPage', 'none');
  CREATE TYPE "public"."enum_categories_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_categories_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_categories_seo_sitemap_change_frequency" AS ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never');
  CREATE TYPE "public"."enum_categories_seo_schema_type" AS ENUM('auto', 'CollectionPage', 'WebPage', 'none');
  CREATE TYPE "public"."enum_posts_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_posts_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_posts_seo_sitemap_change_frequency" AS ENUM('daily', 'weekly', 'monthly', 'yearly');
  CREATE TYPE "public"."enum_posts_seo_schema_type" AS ENUM('auto', 'BlogPosting', 'WebPage', 'none');
  CREATE TYPE "public"."enum_blog_authors_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_blog_authors_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_blog_authors_seo_sitemap_change_frequency" AS ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never');
  CREATE TYPE "public"."enum_blog_authors_seo_schema_type" AS ENUM('auto', 'ProfilePage', 'WebPage', 'none');
  CREATE TYPE "public"."enum_post_categories_seo_robots_index" AS ENUM('index', 'noindex');
  CREATE TYPE "public"."enum_post_categories_seo_robots_follow" AS ENUM('follow', 'nofollow');
  CREATE TYPE "public"."enum_post_categories_seo_sitemap_change_frequency" AS ENUM('always', 'hourly', 'daily', 'weekly', 'monthly', 'yearly', 'never');
  CREATE TYPE "public"."enum_post_categories_seo_schema_type" AS ENUM('auto', 'CollectionPage', 'WebPage', 'none');
  ALTER TABLE "brands" ADD COLUMN "seo_meta_title" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_meta_description" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "brands" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "brands" ADD COLUMN "seo_robots_index" "enum_brands_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "brands" ADD COLUMN "seo_robots_follow" "enum_brands_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "brands" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "brands" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "brands" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "brands" ADD COLUMN "seo_sitemap_change_frequency" "enum_brands_seo_sitemap_change_frequency";
  ALTER TABLE "brands" ADD COLUMN "seo_schema_type" "enum_brands_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "brands" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "products" ADD COLUMN "seo_meta_title" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_meta_description" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "products" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "products" ADD COLUMN "seo_robots_index" "enum_products_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "products" ADD COLUMN "seo_robots_follow" "enum_products_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "products" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "products" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "products" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "products" ADD COLUMN "seo_sitemap_change_frequency" "enum_products_seo_sitemap_change_frequency";
  ALTER TABLE "products" ADD COLUMN "seo_schema_type" "enum_products_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "products" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "categories" ADD COLUMN "seo_meta_title" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_meta_description" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "categories" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "categories" ADD COLUMN "seo_robots_index" "enum_categories_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "categories" ADD COLUMN "seo_robots_follow" "enum_categories_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "categories" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "categories" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "categories" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "categories" ADD COLUMN "seo_sitemap_change_frequency" "enum_categories_seo_sitemap_change_frequency";
  ALTER TABLE "categories" ADD COLUMN "seo_schema_type" "enum_categories_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "categories" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "posts" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "posts" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "posts" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "posts" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "posts" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "posts" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "posts" ADD COLUMN "seo_robots_index" "enum_posts_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "posts" ADD COLUMN "seo_robots_follow" "enum_posts_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "posts" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "posts" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "posts" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "posts" ADD COLUMN "seo_sitemap_change_frequency" "enum_posts_seo_sitemap_change_frequency";
  ALTER TABLE "posts" ADD COLUMN "seo_schema_type" "enum_posts_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "posts" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_meta_title" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_meta_description" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_robots_index" "enum_blog_authors_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "blog_authors" ADD COLUMN "seo_robots_follow" "enum_blog_authors_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "blog_authors" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "blog_authors" ADD COLUMN "seo_sitemap_change_frequency" "enum_blog_authors_seo_sitemap_change_frequency";
  ALTER TABLE "blog_authors" ADD COLUMN "seo_schema_type" "enum_blog_authors_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "blog_authors" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "post_categories" ADD COLUMN "seo_meta_title" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_meta_description" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_focus_keyword" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_breadcrumb_label" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_og_title" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_og_description" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_og_image_id" integer;
  ALTER TABLE "post_categories" ADD COLUMN "seo_twitter_image_id" integer;
  ALTER TABLE "post_categories" ADD COLUMN "seo_robots_index" "enum_post_categories_seo_robots_index" DEFAULT 'index';
  ALTER TABLE "post_categories" ADD COLUMN "seo_robots_follow" "enum_post_categories_seo_robots_follow" DEFAULT 'follow';
  ALTER TABLE "post_categories" ADD COLUMN "seo_canonical_override" varchar;
  ALTER TABLE "post_categories" ADD COLUMN "seo_sitemap_include" boolean DEFAULT true;
  ALTER TABLE "post_categories" ADD COLUMN "seo_sitemap_priority" numeric;
  ALTER TABLE "post_categories" ADD COLUMN "seo_sitemap_change_frequency" "enum_post_categories_seo_sitemap_change_frequency";
  ALTER TABLE "post_categories" ADD COLUMN "seo_schema_type" "enum_post_categories_seo_schema_type" DEFAULT 'auto';
  ALTER TABLE "post_categories" ADD COLUMN "seo_custom_json_ld" jsonb;
  ALTER TABLE "brands" ADD CONSTRAINT "brands_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "brands" ADD CONSTRAINT "brands_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products" ADD CONSTRAINT "products_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "products" ADD CONSTRAINT "products_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "categories" ADD CONSTRAINT "categories_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "categories" ADD CONSTRAINT "categories_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts" ADD CONSTRAINT "posts_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts" ADD CONSTRAINT "posts_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "blog_authors" ADD CONSTRAINT "blog_authors_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "blog_authors" ADD CONSTRAINT "blog_authors_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "post_categories" ADD CONSTRAINT "post_categories_seo_og_image_id_media_id_fk" FOREIGN KEY ("seo_og_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "post_categories" ADD CONSTRAINT "post_categories_seo_twitter_image_id_media_id_fk" FOREIGN KEY ("seo_twitter_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "brands_seo_seo_og_image_idx" ON "brands" USING btree ("seo_og_image_id");
  CREATE INDEX "brands_seo_seo_twitter_image_idx" ON "brands" USING btree ("seo_twitter_image_id");
  CREATE INDEX "products_seo_seo_og_image_idx" ON "products" USING btree ("seo_og_image_id");
  CREATE INDEX "products_seo_seo_twitter_image_idx" ON "products" USING btree ("seo_twitter_image_id");
  CREATE INDEX "categories_seo_seo_og_image_idx" ON "categories" USING btree ("seo_og_image_id");
  CREATE INDEX "categories_seo_seo_twitter_image_idx" ON "categories" USING btree ("seo_twitter_image_id");
  CREATE INDEX "posts_seo_seo_og_image_idx" ON "posts" USING btree ("seo_og_image_id");
  CREATE INDEX "posts_seo_seo_twitter_image_idx" ON "posts" USING btree ("seo_twitter_image_id");
  CREATE INDEX "blog_authors_seo_seo_og_image_idx" ON "blog_authors" USING btree ("seo_og_image_id");
  CREATE INDEX "blog_authors_seo_seo_twitter_image_idx" ON "blog_authors" USING btree ("seo_twitter_image_id");
  CREATE INDEX "post_categories_seo_seo_og_image_idx" ON "post_categories" USING btree ("seo_og_image_id");
  CREATE INDEX "post_categories_seo_seo_twitter_image_idx" ON "post_categories" USING btree ("seo_twitter_image_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "brands" DROP CONSTRAINT "brands_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "brands" DROP CONSTRAINT "brands_seo_twitter_image_id_media_id_fk";
  
  ALTER TABLE "products" DROP CONSTRAINT "products_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "products" DROP CONSTRAINT "products_seo_twitter_image_id_media_id_fk";
  
  ALTER TABLE "categories" DROP CONSTRAINT "categories_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "categories" DROP CONSTRAINT "categories_seo_twitter_image_id_media_id_fk";
  
  ALTER TABLE "posts" DROP CONSTRAINT "posts_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "posts" DROP CONSTRAINT "posts_seo_twitter_image_id_media_id_fk";
  
  ALTER TABLE "blog_authors" DROP CONSTRAINT "blog_authors_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "blog_authors" DROP CONSTRAINT "blog_authors_seo_twitter_image_id_media_id_fk";
  
  ALTER TABLE "post_categories" DROP CONSTRAINT "post_categories_seo_og_image_id_media_id_fk";
  
  ALTER TABLE "post_categories" DROP CONSTRAINT "post_categories_seo_twitter_image_id_media_id_fk";
  
  DROP INDEX "brands_seo_seo_og_image_idx";
  DROP INDEX "brands_seo_seo_twitter_image_idx";
  DROP INDEX "products_seo_seo_og_image_idx";
  DROP INDEX "products_seo_seo_twitter_image_idx";
  DROP INDEX "categories_seo_seo_og_image_idx";
  DROP INDEX "categories_seo_seo_twitter_image_idx";
  DROP INDEX "posts_seo_seo_og_image_idx";
  DROP INDEX "posts_seo_seo_twitter_image_idx";
  DROP INDEX "blog_authors_seo_seo_og_image_idx";
  DROP INDEX "blog_authors_seo_seo_twitter_image_idx";
  DROP INDEX "post_categories_seo_seo_og_image_idx";
  DROP INDEX "post_categories_seo_seo_twitter_image_idx";
  ALTER TABLE "brands" DROP COLUMN "seo_meta_title";
  ALTER TABLE "brands" DROP COLUMN "seo_meta_description";
  ALTER TABLE "brands" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "brands" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "brands" DROP COLUMN "seo_og_title";
  ALTER TABLE "brands" DROP COLUMN "seo_og_description";
  ALTER TABLE "brands" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "brands" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "brands" DROP COLUMN "seo_robots_index";
  ALTER TABLE "brands" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "brands" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "brands" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "brands" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "brands" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "brands" DROP COLUMN "seo_schema_type";
  ALTER TABLE "brands" DROP COLUMN "seo_custom_json_ld";
  ALTER TABLE "products" DROP COLUMN "seo_meta_title";
  ALTER TABLE "products" DROP COLUMN "seo_meta_description";
  ALTER TABLE "products" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "products" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "products" DROP COLUMN "seo_og_title";
  ALTER TABLE "products" DROP COLUMN "seo_og_description";
  ALTER TABLE "products" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "products" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "products" DROP COLUMN "seo_robots_index";
  ALTER TABLE "products" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "products" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "products" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "products" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "products" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "products" DROP COLUMN "seo_schema_type";
  ALTER TABLE "products" DROP COLUMN "seo_custom_json_ld";
  ALTER TABLE "categories" DROP COLUMN "seo_meta_title";
  ALTER TABLE "categories" DROP COLUMN "seo_meta_description";
  ALTER TABLE "categories" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "categories" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "categories" DROP COLUMN "seo_og_title";
  ALTER TABLE "categories" DROP COLUMN "seo_og_description";
  ALTER TABLE "categories" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "categories" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "categories" DROP COLUMN "seo_robots_index";
  ALTER TABLE "categories" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "categories" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "categories" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "categories" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "categories" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "categories" DROP COLUMN "seo_schema_type";
  ALTER TABLE "categories" DROP COLUMN "seo_custom_json_ld";
  ALTER TABLE "posts" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "posts" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "posts" DROP COLUMN "seo_og_title";
  ALTER TABLE "posts" DROP COLUMN "seo_og_description";
  ALTER TABLE "posts" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "posts" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "posts" DROP COLUMN "seo_robots_index";
  ALTER TABLE "posts" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "posts" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "posts" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "posts" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "posts" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "posts" DROP COLUMN "seo_schema_type";
  ALTER TABLE "posts" DROP COLUMN "seo_custom_json_ld";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_meta_title";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_meta_description";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_og_title";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_og_description";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_robots_index";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_schema_type";
  ALTER TABLE "blog_authors" DROP COLUMN "seo_custom_json_ld";
  ALTER TABLE "post_categories" DROP COLUMN "seo_meta_title";
  ALTER TABLE "post_categories" DROP COLUMN "seo_meta_description";
  ALTER TABLE "post_categories" DROP COLUMN "seo_focus_keyword";
  ALTER TABLE "post_categories" DROP COLUMN "seo_breadcrumb_label";
  ALTER TABLE "post_categories" DROP COLUMN "seo_og_title";
  ALTER TABLE "post_categories" DROP COLUMN "seo_og_description";
  ALTER TABLE "post_categories" DROP COLUMN "seo_og_image_id";
  ALTER TABLE "post_categories" DROP COLUMN "seo_twitter_image_id";
  ALTER TABLE "post_categories" DROP COLUMN "seo_robots_index";
  ALTER TABLE "post_categories" DROP COLUMN "seo_robots_follow";
  ALTER TABLE "post_categories" DROP COLUMN "seo_canonical_override";
  ALTER TABLE "post_categories" DROP COLUMN "seo_sitemap_include";
  ALTER TABLE "post_categories" DROP COLUMN "seo_sitemap_priority";
  ALTER TABLE "post_categories" DROP COLUMN "seo_sitemap_change_frequency";
  ALTER TABLE "post_categories" DROP COLUMN "seo_schema_type";
  ALTER TABLE "post_categories" DROP COLUMN "seo_custom_json_ld";
  DROP TYPE "public"."enum_brands_seo_robots_index";
  DROP TYPE "public"."enum_brands_seo_robots_follow";
  DROP TYPE "public"."enum_brands_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_brands_seo_schema_type";
  DROP TYPE "public"."enum_products_seo_robots_index";
  DROP TYPE "public"."enum_products_seo_robots_follow";
  DROP TYPE "public"."enum_products_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_products_seo_schema_type";
  DROP TYPE "public"."enum_categories_seo_robots_index";
  DROP TYPE "public"."enum_categories_seo_robots_follow";
  DROP TYPE "public"."enum_categories_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_categories_seo_schema_type";
  DROP TYPE "public"."enum_posts_seo_robots_index";
  DROP TYPE "public"."enum_posts_seo_robots_follow";
  DROP TYPE "public"."enum_posts_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_posts_seo_schema_type";
  DROP TYPE "public"."enum_blog_authors_seo_robots_index";
  DROP TYPE "public"."enum_blog_authors_seo_robots_follow";
  DROP TYPE "public"."enum_blog_authors_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_blog_authors_seo_schema_type";
  DROP TYPE "public"."enum_post_categories_seo_robots_index";
  DROP TYPE "public"."enum_post_categories_seo_robots_follow";
  DROP TYPE "public"."enum_post_categories_seo_sitemap_change_frequency";
  DROP TYPE "public"."enum_post_categories_seo_schema_type";`)
}
