/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'chat-profiles': ChatProfileAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    brands: Brand;
    products: Product;
    categories: Category;
    orders: Order;
    posts: Post;
    'post-categories': PostCategory;
    messages: Message;
    'chat-profiles': ChatProfile;
    vouchers: Voucher;
    redirects: Redirect;
    attributes: Attribute;
    'attribute-values': AttributeValue;
    carts: Cart;
    'fragrance-notes': FragranceNote;
    reviews: Review;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'chat-profiles': ChatProfilesSelect<false> | ChatProfilesSelect<true>;
    vouchers: VouchersSelect<false> | VouchersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    attributes: AttributesSelect<false> | AttributesSelect<true>;
    'attribute-values': AttributeValuesSelect<false> | AttributeValuesSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'fragrance-notes': FragranceNotesSelect<false> | FragranceNotesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | ChatProfile;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ChatProfileAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  name: string;
  /**
   * Tự động tạo từ tên, có thể chỉnh sửa thủ công để tối ưu SEO
   */
  slug: string;
  logo?: (number | null) | Media;
  /**
   * Bạn có thể dùng trình soạn thảo trực quan hoặc dán mã HTML vào.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Quyết định cách trang chi tiết sản phẩm được render, index và chuyển hướng.
   */
  seoStatus: 'active' | 'temporarily_out_of_stock' | 'discontinued_keep_page' | 'discontinued_redirect';
  /**
   * Sản phẩm được chuyển hướng đến khi trạng thái là discontinued_redirect.
   */
  relatedProduct?: (number | null) | Product;
  title: string;
  sku?: string | null;
  brand: number | Brand;
  categories?: (number | Category)[] | null;
  /**
   * Chọn sản phẩm có biến thể nếu sản phẩm có nhiều dung tích, màu, quy cách...
   */
  productType?: ('simple' | 'variable') | null;
  price: {
    basePrice: number;
    salePrice?: number | null;
    stock?: number | null;
  };
  /**
   * Ảnh sản phẩm nên dùng tỉ lệ 1:1 để hiển thị đẹp.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Hiển thị ở phần đầu trang sản phẩm.
   */
  shortDescription?: string | null;
  /**
   * Dùng cho dung tích, xuất xứ, nhóm hương, loại da, nồng độ...
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Dữ liệu dùng cho bộ lọc danh mục, tìm kiếm và so sánh sản phẩm.
   */
  productAttributes?:
    | {
        attribute: number | Attribute;
        values?: (number | AttributeValue)[] | null;
        /**
         * Dùng khi sản phẩm có giá trị riêng, ví dụ độ lưu hương 7 giờ.
         */
        numericValue?: number | null;
        booleanValue?: boolean | null;
        textValue?: string | null;
        id?: string | null;
      }[]
    | null;
  fragranceProfile?: {
    /**
     * Chọn các nốt hương xuất hiện đầu tiên sau khi xịt.
     */
    topNotes?: (number | FragranceNote)[] | null;
    /**
     * Chọn các nốt hương tạo nên phần lõi của mùi hương.
     */
    middleNotes?: (number | FragranceNote)[] | null;
    /**
     * Chọn các nốt hương lưu lại lâu nhất trên da.
     */
    baseNotes?: (number | FragranceNote)[] | null;
    /**
     * Chấm theo thang điểm 0–10.
     */
    longevityScore?: number | null;
    /**
     * Chấm theo thang điểm 0–10.
     */
    sillageScore?: number | null;
  };
  /**
   * Dùng cho các biến thể như 30ml, 50ml, 100ml, fullbox, tester, màu sắc, quy cách...
   */
  variants?:
    | {
        name: string;
        sku?: string | null;
        isDefault?: boolean | null;
        /**
         * Ví dụ: 50ml, màu đỏ, fullbox hoặc tester.
         */
        optionValues?: (number | AttributeValue)[] | null;
        basePrice: number;
        salePrice?: number | null;
        stock?: number | null;
        image?: (number | null) | Media;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Nội dung chi tiết sản phẩm được convert từ HTML WordPress sang RichText. Giữ H2, H3, list, link, bảng nếu editor hỗ trợ.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isCombo?: boolean | null;
  comboItems?: (number | Product)[] | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Tự động tạo từ tên sản phẩm, có thể chỉnh tay để tối ưu SEO.
   */
  slug: string;
  /**
   * Được tính tự động từ các review đã duyệt.
   */
  averageRating?: number | null;
  /**
   * Tổng số review đã duyệt của sản phẩm.
   */
  reviewCount?: number | null;
  status?: ('draft' | 'published') | null;
  displayLocation?: ('best-seller' | 'combo' | 'new-arrival' | 'flash-sale')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  image?: (number | null) | Media;
  /**
   * Mô tả danh mục đã được convert sang RichText.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tự động tạo từ tên, có thể chỉnh sửa thủ công để tối ưu SEO
   */
  slug: string;
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * Định nghĩa các thuộc tính có cấu trúc như nhóm hương, độ lưu hương, loại da và dung tích.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes".
 */
export interface Attribute {
  id: number;
  name: string;
  /**
   * Khóa ổn định dùng cho API và URL bộ lọc.
   */
  slug: string;
  description?: string | null;
  scope: 'general' | 'fragrance' | 'beauty';
  valueType: 'select' | 'multi_select' | 'number' | 'range' | 'boolean' | 'text';
  unit?: string | null;
  sortOrder?: number | null;
  /**
   * Để trống nếu thuộc tính có thể áp dụng cho mọi danh mục.
   */
  applicableCategories?: (number | Category)[] | null;
  filterable?: boolean | null;
  comparable?: boolean | null;
  variantOption?: boolean | null;
  allowsMultiple?: boolean | null;
  displayStyle?: ('checkbox' | 'radio' | 'dropdown' | 'chips' | 'range' | 'color') | null;
  validation?: {
    min?: number | null;
    max?: number | null;
    step?: number | null;
  };
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Các giá trị chuẩn hóa phục vụ bộ lọc: Floral, Woody, 6 giờ, Da dầu...
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-values".
 */
export interface AttributeValue {
  id: number;
  attribute: number | Attribute;
  label: string;
  /**
   * Hook bảo đảm slug không trùng trong cùng một Attribute.
   */
  slug: string;
  description?: string | null;
  /**
   * Dùng cho độ lưu hương, dung tích, chỉ số hoặc range.
   */
  numericValue?: number | null;
  booleanValue?: boolean | null;
  /**
   * Hỗ trợ tìm kiếm/import: woody, gỗ, hương gỗ.
   */
  aliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  colorHex?: string | null;
  image?: (number | null) | Media;
  sortOrder?: number | null;
  metadata?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Thư viện nốt hương và icon dùng lại cho nhiều sản phẩm nước hoa.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fragrance-notes".
 */
export interface FragranceNote {
  id: number;
  name: string;
  /**
   * Tự tạo từ tên nốt hương. Có thể chỉnh tay.
   */
  slug: string;
  /**
   * Ưu tiên PNG nền trong suốt, icon nét đen đơn sắc.
   */
  icon: number | Media;
  /**
   * Không bắt buộc. Ví dụ: Hương hoa trắng thanh lịch, mềm mại.
   */
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customer?: (number | null) | User;
  customerInfo: {
    fullName: string;
    phone: string;
    email?: string | null;
    address?: string | null;
    province?: string | null;
    district?: string | null;
    ward?: string | null;
  };
  items?:
    | {
        product: number | Product;
        /**
         * ID của biến thể trong products.variants tại thời điểm mua.
         */
        variantId?: string | null;
        productTitleSnapshot: string;
        variantNameSnapshot?: string | null;
        skuSnapshot?: string | null;
        quantity: number;
        priceAtPurchase: number;
        id?: string | null;
      }[]
    | null;
  totalAmount: number;
  paymentMethod?: ('cod' | 'bank_transfer' | 'fundiin') | null;
  status?: ('pending' | 'confirmed' | 'shipping' | 'completed' | 'cancelled') | null;
  fundiin?: {
    transactionId?: string | null;
    paymentStatus?: string | null;
    orderToken?: string | null;
  };
  subtotalAmount?: number | null;
  discountAmount?: number | null;
  voucherCode?: string | null;
  voucherId?: (number | null) | Voucher;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers".
 */
export interface Voucher {
  id: number;
  /**
   * VD: FLASH15, MDF50K, FREESHIP
   */
  code: string;
  title?: string | null;
  status?: ('active' | 'inactive') | null;
  type: 'fixed' | 'percent';
  /**
   * Nếu fixed: nhập 50000. Nếu percent: nhập 10 tương ứng 10%.
   */
  value: number;
  minOrderAmount?: number | null;
  /**
   * Chỉ cần dùng cho voucher phần trăm. VD: giảm 10% tối đa 100.000đ.
   */
  maxDiscountAmount?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  /**
   * Để trống hoặc 0 nếu không giới hạn.
   */
  usageLimit?: number | null;
  usedCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Tự động tạo từ tên, có thể chỉnh sửa thủ công để tối ưu SEO
   */
  slug: string;
  thumbnail: number | Media;
  categories?: (number | PostCategory)[] | null;
  /**
   * Bạn có thể dùng trình soạn thảo trực quan hoặc dán mã HTML vào.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  profile: number | ChatProfile;
  customerName: string;
  sender: 'customer' | 'admin';
  content: string;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-profiles".
 */
export interface ChatProfile {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'chat-profiles';
}
/**
 * Quản lý các URL cũ từ WordPress và lịch sử thay đổi slug.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Ví dụ: /cua-hang/nuoc-hoa-chanel/. Có thể dán URL đầy đủ của maraisdefrance.vn.
   */
  from: string;
  /**
   * Ví dụ: /products/nuoc-hoa-chanel. URL nội bộ sẽ tự động được loại bỏ domain.
   */
  to: string;
  /**
   * Dùng 301 cho migration hoặc thay đổi slug lâu dài. Dùng 302 cho chuyển hướng tạm thời.
   */
  type: '301' | '302';
  /**
   * Tắt để tạm ngừng chuyển hướng mà không xóa bản ghi.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user?: (number | null) | User;
  guestId?: string | null;
  status: 'active' | 'abandoned' | 'converted' | 'merged' | 'expired';
  items?:
    | {
        product: number | Product;
        /**
         * ID row trong products.variants; bắt buộc với variable product.
         */
        variantId?: string | null;
        quantity: number;
        productTitleSnapshot?: string | null;
        variantNameSnapshot?: string | null;
        skuSnapshot?: string | null;
        unitPriceSnapshot?: number | null;
        stockSnapshot?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  voucher?: (number | null) | Voucher;
  subtotalAmount?: number | null;
  discountAmount?: number | null;
  totalAmount?: number | null;
  lastActivityAt?: string | null;
  expiresAt?: string | null;
  convertedOrder?: (number | null) | Order;
  mergedIntoCart?: (number | null) | Cart;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  /**
   * Sản phẩm được khách hàng đánh giá.
   */
  product: number | Product;
  /**
   * Tự động lấy từ người đang đăng nhập. Để trống nếu khách gửi ẩn danh.
   */
  user?: (number | null) | User;
  /**
   * Điểm đánh giá từ 1 đến 5 sao.
   */
  rating: number;
  comment?: string | null;
  /**
   * Chỉ review đã duyệt mới được tính vào điểm trung bình của sản phẩm.
   */
  status: 'pending' | 'approved' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'chat-profiles';
        value: number | ChatProfile;
      } | null)
    | ({
        relationTo: 'vouchers';
        value: number | Voucher;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'attributes';
        value: number | Attribute;
      } | null)
    | ({
        relationTo: 'attribute-values';
        value: number | AttributeValue;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'fragrance-notes';
        value: number | FragranceNote;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'chat-profiles';
        value: number | ChatProfile;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'chat-profiles';
        value: number | ChatProfile;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  description?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  seoStatus?: T;
  relatedProduct?: T;
  title?: T;
  sku?: T;
  brand?: T;
  categories?: T;
  productType?: T;
  price?:
    | T
    | {
        basePrice?: T;
        salePrice?: T;
        stock?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  shortDescription?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  productAttributes?:
    | T
    | {
        attribute?: T;
        values?: T;
        numericValue?: T;
        booleanValue?: T;
        textValue?: T;
        id?: T;
      };
  fragranceProfile?:
    | T
    | {
        topNotes?: T;
        middleNotes?: T;
        baseNotes?: T;
        longevityScore?: T;
        sillageScore?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        isDefault?: T;
        optionValues?: T;
        basePrice?: T;
        salePrice?: T;
        stock?: T;
        image?: T;
        isActive?: T;
        id?: T;
      };
  description?: T;
  isCombo?: T;
  comboItems?: T;
  seoTitle?: T;
  seoDescription?: T;
  slug?: T;
  averageRating?: T;
  reviewCount?: T;
  status?: T;
  displayLocation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  image?: T;
  description?: T;
  slug?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  customerInfo?:
    | T
    | {
        fullName?: T;
        phone?: T;
        email?: T;
        address?: T;
        province?: T;
        district?: T;
        ward?: T;
      };
  items?:
    | T
    | {
        product?: T;
        variantId?: T;
        productTitleSnapshot?: T;
        variantNameSnapshot?: T;
        skuSnapshot?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  totalAmount?: T;
  paymentMethod?: T;
  status?: T;
  fundiin?:
    | T
    | {
        transactionId?: T;
        paymentStatus?: T;
        orderToken?: T;
      };
  subtotalAmount?: T;
  discountAmount?: T;
  voucherCode?: T;
  voucherId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  thumbnail?: T;
  categories?: T;
  content?: T;
  excerpt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  profile?: T;
  customerName?: T;
  sender?: T;
  content?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-profiles_select".
 */
export interface ChatProfilesSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vouchers_select".
 */
export interface VouchersSelect<T extends boolean = true> {
  code?: T;
  title?: T;
  status?: T;
  type?: T;
  value?: T;
  minOrderAmount?: T;
  maxDiscountAmount?: T;
  startsAt?: T;
  endsAt?: T;
  usageLimit?: T;
  usedCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attributes_select".
 */
export interface AttributesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  scope?: T;
  valueType?: T;
  unit?: T;
  sortOrder?: T;
  applicableCategories?: T;
  filterable?: T;
  comparable?: T;
  variantOption?: T;
  allowsMultiple?: T;
  displayStyle?: T;
  validation?:
    | T
    | {
        min?: T;
        max?: T;
        step?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attribute-values_select".
 */
export interface AttributeValuesSelect<T extends boolean = true> {
  attribute?: T;
  label?: T;
  slug?: T;
  description?: T;
  numericValue?: T;
  booleanValue?: T;
  aliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  colorHex?: T;
  image?: T;
  sortOrder?: T;
  metadata?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  guestId?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variantId?: T;
        quantity?: T;
        productTitleSnapshot?: T;
        variantNameSnapshot?: T;
        skuSnapshot?: T;
        unitPriceSnapshot?: T;
        stockSnapshot?: T;
        lineTotal?: T;
        id?: T;
      };
  voucher?: T;
  subtotalAmount?: T;
  discountAmount?: T;
  totalAmount?: T;
  lastActivityAt?: T;
  expiresAt?: T;
  convertedOrder?: T;
  mergedIntoCart?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fragrance-notes_select".
 */
export interface FragranceNotesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  rating?: T;
  comment?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  heroSliders?:
    | {
        imageDesktop: number | Media;
        imageTablet: number | Media;
        imageMobile: number | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  header?: {
    logo?: (number | null) | Media;
    navItems?:
      | {
          label: string;
          link: string;
          id?: string | null;
        }[]
      | null;
  };
  contact?: {
    phone?: string | null;
    zaloLink?: string | null;
    address?: string | null;
    facebookUrl?: string | null;
  };
  flashSale?: {
    enabled?: boolean | null;
    endTime?: string | null;
    /**
     * Chọn tối đa 4 voucher từ kho voucher. Có thể kéo thả để thay đổi thứ tự hiển thị.
     */
    vouchers?: (number | Voucher)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    title?: string | null;
    image?: (number | null) | Media;
  };
  story?: {
    heading?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
  };
  values?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  heroSliders?:
    | T
    | {
        imageDesktop?: T;
        imageTablet?: T;
        imageMobile?: T;
        link?: T;
        id?: T;
      };
  header?:
    | T
    | {
        logo?: T;
        navItems?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        phone?: T;
        zaloLink?: T;
        address?: T;
        facebookUrl?: T;
      };
  flashSale?:
    | T
    | {
        enabled?: T;
        endTime?: T;
        vouchers?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        image?: T;
      };
  story?:
    | T
    | {
        heading?: T;
        content?: T;
        image?: T;
      };
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}