name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/tika299/mfparis:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}
            NEXT_PUBLIC_BASE_URL=https://maraisdefrance.vn
            NEXT_PUBLIC_SERVER_URL=https://maraisdefrance.vn
            NEXT_PUBLIC_SOCKET_URL=https://socket.maraisdefrance.vn
            SOCKET_SERVER_URL=https://socket.maraisdefrance.vn
            MEDIA_DIR=/app/media
